 		return "CREATE TABLE IF NOT EXISTS Branch(BranchID varchar (20) PRIMARY KEY, street char (15) NOT NULL, city char (15) NOT NULL, zone char (15) NOT NULL);
				CREATE TABLE IF NOT EXISTS BrContacttable( PhoneNo int (15) PRIMARY KEY, email varchar (25) NOT NULL, BranchID VARCHAR (20), FOREIGN KEY (BranchID) REFERENCES Branch (BranchID));	
				CREATE TABLE IF NOT EXISTS Accountant(StaffId int PRIMARY KEY, BranchID varchar (20), Fname char (10) NOT NULL, Lname char (10), DOB DATE NOT NULL, Salary int (15) NOT NULL, computerAllowance char (3) NOT NULL, FOREIGN KEY (BranchID) REFERENCES Branch (BranchID));
				CREATE TABLE IF NOT EXISTS Advertisement(AdvertID int PRIMARY KEY, AdvertDateTime DATE, Mentions int (11), Airtime int (15), Spotno int (2), PageSize CHAR (10), StaffID int, FOREIGN KEY (StaffID) REFERENCES Accountant (StaffID));
				CREATE TABLE IF NOT EXISTS Assignment(AssigntID int PRIMARY KEY, BranchID varchar (20), AssigntDateTime DATE, AdvertID int, FOREIGN KEY (BranchID) REFERENCES Branch (BranchID), FOREIGN KEY (AdvertID) REFERENCES Advertisement (AdvertID));
				CREATE TABLE IF NOT EXISTS Client(ClientNo int PRIMARY KEY AUTO_INCREMENT, Fname char (10) NOT NULL, Lname char (10) NOT NULL, street char (10), city char (10) NOT NULL, zone char (10), BranchID varchar (20), FOREIGN KEY (BranchID) REFERENCES Branch (BranchID));
				CREATE TABLE IF NOT EXISTS Application(AdvertID int, ClientNo int, FOREIGN KEY (AdvertID) REFERENCES Advertisement (AdvertID), FOREIGN KEY (ClientNo) REFERENCES Client (ClientNo));
				CREATE TABLE IF NOT EXISTS CliContact( PhoneNo int PRIMARY KEY, email varchar (30), ClientNo int, FOREIGN KEY (ClientNo) REFERENCES Client (ClientNo));
				CREATE TABLE IF NOT EXISTS Manager(StaffID int PRIMARY KEY, BranchID varchar (20), Fname char (10) NOT NULL, Lname char (10), DOB DATE NOT NULL, Salary int (15) NOT NULL, MgrStartDate DATE NOT NULL, bonus int, FOREIGN KEY (BranchID) REFERENCES Branch (BranchID));
				CREATE TABLE IF NOT EXISTS Sales_Executive(StaffID int PRIMARY KEY, BranchID varchar (20), Fname char (10) NOT NULL, Lname char (10), DOB DATE NOT NULL, Salary int (15) NOT NULL, salesArea char (15), carAllowance char (3) NOT NULL, FOREIGN KEY (BranchID) REFERENCES Branch (BranchID));
				CREATE TABLE IF NOT EXISTS Designer(StaffId int PRIMARY KEY, BranchID varchar (20), Fname char (10) NOT NULL, Lname char (10), DOB DATE NOT NULL, Salary int (15) NOT NULL, TimeAllowance char (3) NOT NULL, FOREIGN KEY (BranchID) REFERENCES Branch (BranchID));
				CREATE TABLE IF NOT EXISTS Auditor(StaffId int PRIMARY KEY, BranchID varchar (20), Fname char (10) NOT NULL, Lname char (10), DOB DATE NOT NULL, Salary int (15) NOT NULL, Report char (3) NOT NULL, FOREIGN KEY (BranchID) REFERENCES Branch (BranchID));
				CREATE TABLE IF NOT EXISTS Booking_Clerk(StaffId int PRIMARY KEY, BranchID varchar (20), Fname char (10) NOT NULL, Lname char (10), DOB DATE NOT NULL, Salary int (15) NOT NULL, Orders int NOT NULL, FOREIGN KEY (BranchID) REFERENCES Branch (BranchID));
				CREATE TABLE IF NOT EXISTS Debt_Collector(StaffId int PRIMARY KEY, BranchID varchar (20), Fname char (10) NOT NULL, Lname char (10), DOB DATE NOT NULL, Salary int (15) NOT NULL, transportAllowance int NOT NULL, FOREIGN KEY (BranchID) REFERENCES Branch (BranchID));)";
	}
